/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/* Exercise to turn on LED2 of B-L475IOTA
 *
 * LED2 (green) is configured under PB14 GPIO
 *
 * Instructions for GPIO/LED blink
 * AHB2 base - 0x4002 4400
 * AHB2_ENR offset - 0x4C
 * GPIOB base reg 0x4800 0400 + offset 0x00 for mode
 * Configure mode reg (bits 28/29) set to 01
 * configure output mode (offset 0x14 / OD14)
 *
 */


int main(void)
{

	uint32_t *RCC_AHB2ENR = (uint32_t*)0x4002104C;
	uint32_t *pPortBModeReg = (uint32_t*)0x48000400;
	uint32_t *pPortBOutReg = (uint32_t*)0x48000414;

	*RCC_AHB2ENR |= 0x02; //enable clock

	*pPortBModeReg &= 0xCFFFFFFF; //config mode reg, clear 28/29 bits
	*pPortBModeReg |= 0x10000000; //set 28th bit

	*pPortBOutReg |= 0x4000;


	while (1);

    /* Loop forever */
	for(;;);
}
